list = [    'Beyonce', 
            'BillieEilish', 
            'CharliePuth',
            'ColdPlay', 
            'Drake', 
            'DuaLipa',
            'EdSheeran',
            'JustinBieber',
            'KatyPerry',
            'LadyGaga',
            'Maroon5',
            'NickiMinaj',
            'Rihanna',
            'SelenaGomez',
            'TaylorSwift',
            ]

list_with_spaces = ['Beyonce', 
                    'Billie Eilish', 
                    'Charlie Puth',
                    'ColdPlay', 
                    'Drake', 
                    'Dua Lipa',
                    'Ed Sheeran',
                    'Justin Bieber',
                    'Katy Perry',
                    'Lady Gaga',
                    'Maroon 5',
                    'Nicki Minaj',
                    'Rihanna',
                    'Selena Gomez',
                    'Taylor Swift',
                    'beyoncé',
                    'verse',
                    'chris martin',
                    'sean paul',
                    'justin timberlake',
                    'beyoncè'
                    ]

